In [18]:
import pandas as pd

In [19]:
df_mbu = pd.read_excel('/content/MBU_Entry_Status_District_Wise 15-07-2026 12-10-17 PM.xlsx')

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [20]:
df_mbu.head()

,MBU_Entry_Status_District_Wise,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,CHHATTISGARH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Generated Date(DD-MM-YYYY) : 15-07-2026 12:10:...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,District Name,District Code,Academic Year,Total Student,Total Students AADHAAR Provided,AADHAAR Verified-Passed(Yes),AADHAAR Verified-Failed(No),AADHAAR Verified-To be Done,MBU Pending (Age 5-15),MBU Pending (Age 15 and above),MBU Not Required,MBU Not Applicable,Status Check to be done
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13)
4,BALOD,2222,2025-26,28,27,24,3,0,0,0,24,0,0

In [21]:
df_mbu.columns = df_mbu.iloc[2]

In [22]:
df_mbu.head()

2,District Name,District Code,Academic Year,Total Student,Total Students AADHAAR Provided,AADHAAR Verified-Passed(Yes),AADHAAR Verified-Failed(No),AADHAAR Verified-To be Done,MBU Pending (Age 5-15),MBU Pending (Age 15 and above),MBU Not Required,MBU Not Applicable,Status Check to be done
0,CHHATTISGARH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Generated Date(DD-MM-YYYY) : 15-07-2026 12:10:...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,District Name,District Code,Academic Year,Total Student,Total Students AADHAAR Provided,AADHAAR Verified-Passed(Yes),AADHAAR Verified-Failed(No),AADHAAR Verified-To be Done,MBU Pending (Age 5-15),MBU Pending (Age 15 and above),MBU Not Required,MBU Not Applicable,Status Check to be done
3,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13)
4,BALOD,2222,2025-26,28,27,24,3,0,0,0,24,0,0

In [23]:
df_mbu = df_mbu.iloc[3:]
df_mbu.reset_index(drop=True , inplace=True)

In [24]:
df_mbu.head()

2,District Name,District Code,Academic Year,Total Student,Total Students AADHAAR Provided,AADHAAR Verified-Passed(Yes),AADHAAR Verified-Failed(No),AADHAAR Verified-To be Done,MBU Pending (Age 5-15),MBU Pending (Age 15 and above),MBU Not Required,MBU Not Applicable,Status Check to be done
0,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13)
1,BALOD,2222,2025-26,28,27,24,3,0,0,0,24,0,0
2,BALOD,2222,2026-27,124282,123608,115650,7573,385,4989,8032,102628,0,1
3,BALODABAZAR,2224,2025-26,14175,13929,12660,1264,5,293,2491,9875,0,1
4,BALODABAZAR,2224,2026-27,215368,211289,201670,8873,746,10998,16286,174375,1,10

In [25]:
df_mbu = df_mbu.iloc[1:]
df_mbu.reset_index(drop=True , inplace=True)

In [27]:
df_mbu.head()

2,District Name,District Code,Academic Year,Total Student,Total Students AADHAAR Provided,AADHAAR Verified-Passed(Yes),AADHAAR Verified-Failed(No),AADHAAR Verified-To be Done,MBU Pending (Age 5-15),MBU Pending (Age 15 and above),MBU Not Required,MBU Not Applicable,Status Check to be done
0,BALOD,2222,2025-26,28,27,24,3,0,0,0,24,0,0
1,BALOD,2222,2026-27,124282,123608,115650,7573,385,4989,8032,102628,0,1
2,BALODABAZAR,2224,2025-26,14175,13929,12660,1264,5,293,2491,9875,0,1
3,BALODABAZAR,2224,2026-27,215368,211289,201670,8873,746,10998,16286,174375,1,10
4,BALRAMPUR,2226,2025-26,4944,4321,3334,987,0,53,56,3221,0,4

In [29]:
columns_to_aggregate = [
    'District Name',
    'MBU Pending (Age 5-15)',
    'MBU Pending (Age 15 and above)',
    'Total Students AADHAAR Provided'
]

df_selected_agg = df_mbu[columns_to_aggregate].copy()

# Convert specified columns to numeric
for col in columns_to_aggregate[1:]:
    df_selected_agg[col] = pd.to_numeric(df_selected_agg[col], errors='coerce')

# Group by 'District Name' and sum the selected numeric columns
df_final_aggregated = df_selected_agg.groupby('District Name', as_index=False).sum()

# Display the aggregated DataFrame
display(df_final_aggregated.head())

2,District Name,MBU Pending (Age 5-15),MBU Pending (Age 15 and above),Total Students AADHAAR Provided
0,BALOD,4989,8032,123635
1,BALODABAZAR,11291,18777,225218
2,BALRAMPUR,1691,421,143596
3,BASTER,2936,1358,144730
4,BEMETARA,7221,6626,160187

In [30]:
df_final_aggregated['total pending'] = df_final_aggregated['MBU Pending (Age 5-15)'] + df_final_aggregated['MBU Pending (Age 15 and above)']
display(df_final_aggregated.head())

2,District Name,MBU Pending (Age 5-15),MBU Pending (Age 15 and above),Total Students AADHAAR Provided,total pending
0,BALOD,4989,8032,123635,13021
1,BALODABAZAR,11291,18777,225218,30068
2,BALRAMPUR,1691,421,143596,2112
3,BASTER,2936,1358,144730,4294
4,BEMETARA,7221,6626,160187,13847

In [32]:
import numpy as np

# Calculate 'Total Pending %', handling division by zero
df_final_aggregated['Total Pending %'] = np.where(
    df_final_aggregated['Total Students AADHAAR Provided'] != 0,
    (df_final_aggregated['total pending'] / df_final_aggregated['Total Students AADHAAR Provided']) * 100,
    0  # Assign 0% if 'Total Students AADHAAR Provided' is zero
).round(2)
display(df_final_aggregated.head())

2,District Name,MBU Pending (Age 5-15),MBU Pending (Age 15 and above),Total Students AADHAAR Provided,total pending,Total Pending %
0,BALOD,4989,8032,123635,13021,10.53
1,BALODABAZAR,11291,18777,225218,30068,13.35
2,BALRAMPUR,1691,421,143596,2112,1.47
3,BASTER,2936,1358,144730,4294,2.97
4,BEMETARA,7221,6626,160187,13847,8.64